"""Storage interfaces."""

from __future__ import annotations

from typing import Any, Protocol, Sequence

from advanced_graphrag.domain import (
    Chunk,
    Community,
    CommunitySummary,
    Document,
    Entity,
    Relationship,
)


class GraphStore(Protocol):
    def upsert_document(self, document: Document) -> None: ...
    def upsert_chunks(self, chunks: Sequence[Chunk]) -> None: ...
    def upsert_entities(self, entities: Sequence[Entity]) -> None: ...
    def upsert_relationships(self, relationships: Sequence[Relationship]) -> None: ...
    def upsert_communities(self, communities: Sequence[Community]) -> None: ...
    def upsert_community_summaries(self, summaries: Sequence[CommunitySummary]) -> None: ...
    def get_chunk(self, chunk_id: str) -> Chunk | None: ...
    def get_entity(self, entity_id: str) -> Entity | None: ...
    def entities(self) -> list[Entity]: ...
    def relationships(self) -> list[Relationship]: ...
    def chunks(self) -> list[Chunk]: ...
    def community_summaries(self) -> list[CommunitySummary]: ...
    def neighbors(self, entity_id: str) -> list[tuple[str, Relationship]]: ...
    def symbolic_read(self, query: str) -> list[dict[str, Any]]: ...


class VectorStore(Protocol):
    def upsert(self, namespace: str, items: Sequence[tuple[str, str, Sequence[float], dict[str, Any]]]) -> None: ...
    def search(
        self,
        namespace: str,
        query_vector: Sequence[float],
        *,
        top_k: int,
        filters: dict[str, Any] | None = None,
    ) -> list[tuple[str, float, dict[str, Any]]]: ...


class ArtifactStore(Protocol):
    def put_json(self, key: str, value: dict[str, Any]) -> None: ...
    def get_json(self, key: str) -> dict[str, Any] | None: ...

